### ISSUE TITLE
Route enters twice

### ISSUE THREAD

**Issue by styper** [Danangjoyoo/flask-http-middleware#9]
Hello

First I'd like to thank you for the great plug-in, it's very helpful!

I'm not sure why, but when I activate the Middleware manager, the route gets called twice per request.

OS: Win 11
Python: 3.12.0
Flask version: 3.0.0
Flask-http-middleware: 0.4.0

Example:
```python
from flask import Flask
from flask_http_middleware import MiddlewareManager
import time

app = Flask("flask")

@app.get("/dummy")
def dummy():
    print("Entered dummy " + str(time.perf_counter()))
    return {"dummy": "dummy"}

app.wsgi_app = MiddlewareManager(app)

if __name__ == "__main__":
    app.run()
```

And this is the console result:
```
* Serving Flask app 'flask'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
Entered dummy 65040.6774082
Entered dummy 65040.6775903
127.0.0.1 - - [02/Nov/2023 14:10:47] "GET /dummy HTTP/1.1" 200 -
```

You can see that the endpoint was called once, but the print happened twice. If I comment out the MiddlewareManager I only see one print.

**Comment by Danangjoyoo** [comment]
Hi, I've just fixed this, kindly update to 0.4.1 🙇

**Comment by Danangjoyoo** [comment]
@styper kindly update if you found any issues again!

**Comment by styper** [comment]
@Danangjoyoo Tested and working! Thank you!

**Comment by styper** [comment]
Seems like the bug still happens when there's an exception in-route:

```python
from flask import Flask
from flask_http_middleware import MiddlewareManager
import time
from importlib.metadata import version

app = Flask("flask")

@app.get("/dummy")
def dummy():
    print("Entered dummy " + str(time.perf_counter()))
    return {"dummy": 1/0}

app.wsgi_app = MiddlewareManager(app)

if __name__ == "__main__":
    print('flask_http_middleware: ' + version('flask_http_middleware'))
    print('flask: ' + version('flask'))
    app.run()
```

Output:
```
flask_http_middleware: 0.4.1
flask: 3.0.0
 * Serving Flask app 'flask'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
Entered dummy 129402.6574227
Entered dummy 129402.6574987
[2023-11-03 08:03:28,717] ERROR in app: Exception on /dummy [GET]
Traceback (most recent call last):
  File "...\Python312\Lib\site-packages\flask_http_middleware\manager.py", line 84, in dispatch_request
    return self.app.ensure_sync(self.app.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\teste4.py", line 11, in dummy
    return {"dummy": 1/0}
                     ~^~
ZeroDivisionError: division by zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "...\Python312\Lib\site-packages\flask_http_middleware\manager.py", line 186, in __dispatch_python_2_3_x
    rv = self.app.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\Python312\Lib\site-packages\flask_http_middleware\manager.py", line 183, in __dispatch_python_2_3_x
    rv = self.dispatch_request(request)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\Python312\Lib\site-packages\flask_http_middleware\manager.py", line 86, in dispatch_request
    return self.app.view_functions[rule.endpoint](**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\teste4.py", line 11, in dummy
    return {"dummy": 1/0}
                     ~^~
ZeroDivisionError: division by zero
127.0.0.1 - - [03/Nov/2023 08:03:28] "GET /dummy HTTP/1.1" 500 -
```

Same behavior, if I comment out the MiddlewareManager the route gets called once.

**Comment by Danangjoyoo** [comment]
@styper Hi, the fix already released, please kindly check!

**Comment by styper** [comment]
@Danangjoyoo Tested and working, thank you!
